### ISSUE TITLE
Update getting started with butterfly for version 0.0.03

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/butterfly#101]

**Comment by MaxMarschall** [comment]
Dear Mostapha, I am new to Butterfly, CFD and Github, so please bear with me if I am about to ask a silly question ;)
I can't find the "Load Probes Values" component (https://github.com/mostaphaRoudsari/Butterfly/issues/61). All I have is the "Watch Probes" component without the "probes_" input. I see you have uploaded a new Butterfly release (0.0.03), so is the above component part of that? In that case, how do I get the new version? I tried hitting "update_" on the "Butterfly" component, but nothing has changed. Do I need to update manually?
Cheers,
Max

**Comment by MaxMarschall** [comment]
> I tried hitting "update_" on the "Butterfly" component, but nothing has changed. Do I need to update manually?

Restarted Rhino and GH - Butterfly has indeed updated to 0.0.03 but there seems to be a problem...
![capture](https://cloud.githubusercontent.com/assets/23235030/19963439/b1e394e4-a1bc-11e6-9853-e1bce8f40654.PNG)

**Comment by MaxMarschall** [comment]
Sorry, I was still using the old example file...seems to be working now!

**Comment by mostaphaRoudsari** [comment]
Hi @MaxMarschall, Can you zip and share the case folder with me? It's hard to say why it's failing without checking the file. By default, addLayer is set to False in snappyHexMeshDict.

**Comment by MaxMarschall** [comment]
Hi @mostaphaRoudsari , here is the folder. Thanks for your help!
[towers.zip](https://github.com/mostaphaRoudsari/Butterfly/files/571183/towers.zip)

**Comment by MaxMarschall** [comment]
Hey @mostaphaRoudsari, another thing is that now when I open your outdoor example file, without touching anything the wind tunnel looks like this:

![mesh](https://cloud.githubusercontent.com/assets/23235030/20007901/a6a06f02-a29e-11e6-86ea-312ceda9a44e.jpg)
![pts](https://cloud.githubusercontent.com/assets/23235030/20007902/a6a5adb4-a29e-11e6-9823-f4c97e1a626f.jpg)

Any idea what is going on here?
Cheers,
Max

**Comment by mostaphaRoudsari** [comment]
Hi Max, This looks like a bug that deserves a new issue. I won't have time to check it today but will check both of your cases later this weekend. Thanks.

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall, one more question. what's the windVector in your case? Butterfly is calculating blockMeshDict wrong.

**Comment by MaxMarschall** [comment]
@mostaphaRoudsari thanks, that would be great!
In my case the wind vector was {0.0,7.0,0.0}

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall,

The meshing issue is happening because in `snappyHexMeshDict`, `addLayer` is set to `true` but there was no layers key in the dictionary. This is now fixed if you update to the latest  commit.

I couldn't recreate the second error but I'm really interested to see how did you create it. If you are able to recreate the issue please open a new issue and upload the definition. Thanks!

**Comment by mostaphaRoudsari** [comment]
Updated both text and images!
