### ISSUE TITLE
"-force option"

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-analysis-tools/butterfly#106]
Hello,

The snappyHexMesh component just gave me this error:

> 1. Solution exception:
>  --> OpenFOAM command Failed!
> --> FOAM FATAL ERROR: 
> Case is already decomposed with 6 domains, use the -force option or manually
> remove processor directories before decomposing. e.g.,
>     rm -rf /home/ofuser/workingDir/butterfly/towers5/processor*
> 
> 
>     From function int main(int, char**)
>     in file decomposePar.C at line 358.
> 
> FOAM exiting

Not sure what this means...? 

Btw could someone please take a look at my definition and let me know if any of my starting parameters seem off? I've been having trouble getting any results at all lately, maybe I'm missing something obvious.
![def](https://cloud.githubusercontent.com/assets/23235030/20209924/3d610624-a7f7-11e6-8f79-7af79c73c87e.png)

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall 

The error you get means that a decomposePar command is given in an already decomposed folder. Usually BF takes care to clean a folder between the different steps. Are you following my manual idea or is this purely BF? Try and delete the case folder from User/Name/butterfly and run the steps again. I can't see a reason the case should be decomposed before SHM so it must be smth persisting from a previous run.

My computer is currently running some intensive calculations in Rhino, I have already downloaded your definition and will try it out asap.

Kind regards,
Theodore.

**Comment by MaxMarschall** [comment]
Hi @TheodoreGalanos,

Do you mean your idea about how to get the wind tunnel to fit the landscape? No, I was trying here to run a simplified version since I was having trouble getting results at all. The wind tunnel factors are 1 so it is slightly bigger than the landscape just as before. I also simplified the landscape (it is flat with some extruded surrounding buildings).

I tried to purge the case which didn't help, but then I ran it under a new name which seems to have worked.

On a side note, I realized that one of the surrounding buildings wasn't a closed polysrf. How does BF/OpenFoam handle such situations?

Regards,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall 

Glad it worked. It was smth to do with the case already being decomposed and BF not purging or smth.

Concerning the open polysurface, BF as OF have no problem with open polysurfaces. But your model will have issues since SHM will consider it as part of the mesh and mesh the interior :)

If you are running an outdoor case this would mean artifacts inside so make sure to close it.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
I assume you have stopped the run by setting the run to False in the middle of the run. Butterfly currently doesn't remove decomposed folders when you terminate the analysis. I added a new github issue to take care of this. For now you have to remove them manually from the folder.

**Comment by mimarilker** [comment]
"Butterfly currently doesn't remove decomposed folders when you terminate the analysis."

However, this is not valid for a re-opened case (which is converged), I opened an issue about it.
