### ISSUE TITLE
Load Case

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-analysis-tools/butterfly#117]
Hello,

Rhino crashed, apparently after the mesh was created (looking at the log file). Reconstructparmesh.log also shows no errors. Is there a way to load the mesh back into the GH definition without recalculating it, in order to start the simulation?

I tried this, but it seems to be the wrong component:
![unbenannt](https://cloud.githubusercontent.com/assets/23235030/20530508/dfbc3efe-b0d3-11e6-9a4e-7029a1ef4177.PNG)

Cheers,
Max

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall this is much easier to debug if you share the folder. Is that possible?

**Comment by MaxMarschall** [comment]
Hi @mostaphaRoudsari ,
The case folder is 133mb. However, the error is the same when I try to reopen a case folder with your example files:

![unbenannt](https://cloud.githubusercontent.com/assets/23235030/20591885/19b83b46-b22b-11e6-9751-003df13ee0a5.PNG)

Maybe I'm just using the `CreateCaseFromFolder `component wrongly?

**Comment by MaxMarschall** [comment]
Dear @mostaphaRoudsari ,

Is there a solution to this? I ran a case for a couple of time steps the other day, and now I want to continue the simulation from the last time step without overwriting the case and going through the whole SHM process. Is this possible?

Cheers,
Max

**Comment by mostaphaRoudsari** [comment]
@MaxMarschall sorry for the very late reply. In theory it should work as you're using it. Not sure what's wrong with this case. I'm making a couple of changes in the process of loading stl files which I hope fixes this issue too. I understand that you won't be able to test this for a couple of months but let me know once you get a chance to test it.

**Comment by mostaphaRoudsari** [comment]
Fixed via https://github.com/ladybug-analysis-tools/butterfly/commit/0fb8ef770ebf8a08ad66b3c203640524b9fec74b
@MaxMarschall please re-open this issue if you find a case that fails.

**Comment by MaxMarschall** [comment]
Thanks @mostaphaRoudsari , will give it a go as soon as I can!
