### ISSUE TITLE
Vertical section and legend parameter

### ISSUE THREAD

**Issue by frank984** [ladybug-analysis-tools/butterfly#121]
If I consider a vertical section as reported below:

![cattura1](https://cloud.githubusercontent.com/assets/6491927/20794957/1af49d8e-b7cf-11e6-8628-b1eac0d1e834.JPG)

and I try to visualize the mesh of output data and the relative legend, there is an error with the legend:

![cattura2](https://cloud.githubusercontent.com/assets/6491927/20794995/48a0b4f2-b7cf-11e6-9c90-3f24c66891a2.JPG)

**Comment by mostaphaRoudsari** [comment]
This is a Ladybug issue and butterfly. I will leave this open so we don't forget to get it fixed. Meanwhile you can use create legend component from ladybug to create a vertical legend.

**Comment by mostaphaRoudsari** [comment]
This is fixed now: https://github.com/mostaphaRoudsari/ladybug/pull/340
