### ISSUE TITLE
CFD Calibration process?

### ISSUE THREAD

**Issue by the-donn** [ladybug-analysis-tools/butterfly#129]
In order to trust the output from a simulation, particularly one with such unfathomable parameters as CFD, we have developed a calibration process.The Architectural Institute of Japan web site of calibration files is a great starting point. http://www.aij.or.jp/jpn/publish/cfdguide/index_e.htm

Our in-house starter for a reliable calibration model is a 5 x 5 grid of urban scale buildings. 

However, when I modify your working outdoor example file with one brep to accept a brep of a 5 x 5 array I can get as far as <snappyhexmesh> when I get an error message. I suspect I may need to break the mesh up somehow into focus building (4 rows in, with the other 24 buildings as some lower resolution surroundings)?
Currently I get the following error Message:
![image](https://cloud.githubusercontent.com/assets/15050085/21250722/33f0a2ae-c3ac-11e6-871b-498fc01dadb4.png)

**Comment by TheodoreGalanos** [comment]
Hi @the-donn 

It seems like you are running out of memory? What is the machine you are using atm?

Also, this happens due to VM settings. You should try stopping the default process, then going to settings and allowing more RAM memory use at VM. Mine had 4gb as a default, which gave me the same error in more complicated studies.

Let us know if that fixes it!

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi @the-donn, Any updates on this? I will be happy to help you create the model and give it a try. As @TheodoreGalanos mentioned make sure that VM settings is set up correctly. You should not be running out of RAM for such a simple case.

**Comment by saket411** [comment]
I got the same issue. I disconnected _cellSizeXYZ_ panel and set it to default {1, 1, 1}.
The error will go away.

**Comment by mostaphaRoudsari** [comment]
@saket411 here is where you can increase RAM access for the VM. In order to be able to adjust the value you need to turn off the default machine.

![image](https://cloud.githubusercontent.com/assets/2915573/21754232/51c24b5e-d5ca-11e6-9675-dbaf84b270d4.png)

**Comment by TheodoreGalanos** [comment]
I think I will close this. This was almost certainly a memory issue. @the-donn @saket411 please feel free to re-open if any new information comes around.

**Comment by saket411** [comment]
Adding few comments from my side. 
I was trying to run a urban scale outdoor wind analysis. The buildings with the contours were not working, SHM would throw memory error sometimes or mesh an empty box in most cases. I separated the buildings on a flat plane and meshed - it worked. I separated the 'contour only' and meshed - it worked. But if I combined them, it would mesh an empty box. I believe the contours were very complex. 
I used Drape yesterday to recreate the contours and added the buildings, it works perfectly now. Although it did give a memory error but it was a genuine memory issue I believe. I had set the limit to 18M cells and total cells for refinement reached 42M or something like that. I assigned 28GB to the VM though. 
Whenever memory error pops I rename the case and re run the analysis, usually it works.

**Comment by saket411** [comment]
Hello all,

I have been repeatedly getting memory error after running SHM. error log attached.

I know its a weird question but can someone help in figuring out how much memory I would need to run 20M/40M cells. With 24GB (out of 32) given to VM I was able to successfully run 10M cells. 
Would be great for future reference as well if there can be an approx. memory to no. of cells relation. 
[memory error.zip](https://github.com/ladybug-analysis-tools/butterfly/files/743649/memory.error.zip)
@**TheodoreGalanos** @**mostaphaRoudsari**  Your advice on this would be very helpful.

Thanks a lot!!
