### ISSUE TITLE
Recalculation on every launch

### ISSUE THREAD

**Issue by mimarilker** [ladybug-analysis-tools/butterfly#136]
Hi,

I have reviewed outdoor_airflow sample, with the instructions that I mentioned it runs succesfully, however when I saved and reopened the sample file, Butterfly recalculates everything from start e.g. blockmesh, snappyhexmesh, running solution etc. I have tried to lock solver, however it only works in a recently open file. Is there any way to prevent butterfly run when there is an existing solution folder.

Moreover, it takes too much time to get probe values back from OF, there should be a way to import all point data in a single run, so there will be no need to apply OF for every location change of cutplane (new component that I created). 

Lastly, I have created a visualisation component just works with 4 inputs, and a definiton for "dynamic pressure" which is so important for building aerodynamic analyses.

**Comment by TheodoreGalanos** [comment]
Hi @mimarilker 

Concerning the first point I feel this isn't a BF issue but a Grasshopper one. Historically the way we are handling this is to either freeze the solver on opening or make sure to turn all toggles to false before saving. Andrew has made a nice boolean toggle that resets to false automatically, I believe it is part of Honeybee now but you can also download it from here: https://bitbucket.org/andheum/falsestarttoggle/overview

From my GH experience so far I think this little component is a blessing.

It's really early in the day for me here, I will check the new components when I get to the office. By loading all probe values do you mean that you want to change the location of your cutplane and make it update faster than loading it every time? Wouldn't that require probe values in the whole domain? I would guess smth like a sampledsurface would be independent from needing to produce probe values, if we are talking about post-processing visualization and not run-time visualization.

Concerning dynamic pressure does the new component calculate 0.5*rho*U^2?

Kind regards,
Theodore.

**Comment by mimarilker** [comment]
I will try false start toggle, It will also save a lot of time for Butterfly users for sure. As to visualisation I am mentioning about post processing which is a very important part of cfd simulation

**Comment by mostaphaRoudsari** [comment]
1. To avoid recalculation just set the Boolean for meshing components to False. Next time that you open the file you can bypass both component and connect the case directly to the solution. Butterfly will look under `polyMesh` folder for the mesh and will run if the mesh is available.

2. Similar to 1 if you ran the analysis before you can load them w/o re-running the case. Loading all the points to Grasshopper won't work well in Grasshopper. Maybe we should import them as a point cloud so it takes less RAM. Probes gives the user the flexibility to control number of points to be imported.

**Comment by mostaphaRoudsari** [comment]
The visualization has been discussed in other issues. Closing this one!
