### ISSUE TITLE
input geometry scale

### ISSUE THREAD

**Issue by mehrzad69** [ladybug-analysis-tools/butterfly#137]
Hi,
I have two questions about outdoor-airflow:

1-	I try to run outdoor-airflow sample with a 30 x 30 x 150 meter box as a input geometry and velocity vectors doesn’t change. It seems something wrong.  But when I try smaller geometries everything goes well. Is this a bug?

2-	If I want to change the input geometries scale should I change the wind speed or any other parameters?

**Comment by TheodoreGalanos** [comment]
Hi @mehrzad69 

I cannot be sure what is wrong there without seeing the case setup and definition. The scale of objects should have no impact to the results, provided that the wind tunnel is scaled accordingly which BF takes care of. Ofc the results should differ as the configurations are different. Wind speed and other parameters do not need to be changed however for that to happen.

Kind regards,
Theodore.

**Comment by mimarilker** [comment]
Actually when you scaled the geometry uniformly, you have to use Reynolds Smilarity, but you should be so careful in doing this. Make a research about similarity types, if you need additional help, please  keep on to write this issue.

**Comment by TheodoreGalanos** [comment]
@mimarilker Is that if you want to retain the (scale of?) results in the scaled case? I've never had to do such a transformation so far, sounds interesting.

I was under the impression the OP was reporting that his case was not affected by changing the scale of the input geometry, in which case I would think it's an issue of setting up the definition (e.g. old input was internalized) and it wouldn't be related to the physical parameters of the case.

Kind regards,
Theodore.

**Comment by mimarilker** [comment]
Of course, scaling cannot change results, its valid for all of the cfd packages I know, however you should get different results, for this purpose, if you are applying geometrical similarity, then you should use reynolds similarity. It means that, lets say, base geometry is scaled at a rate of 10, so the velocity input should change at the same rate, briefly if it was 2 m/s than it should be changed to 20 m/s. I am exactly sure about that, btw I am an academician (architect and wind engineer) not a cfd specialist, so please check it yourself to be sure.

**Comment by mehrzad69** [comment]
hi @TheodoreGalanos ,
thank you for your respond. The case and the screenshot attached which show the velocity vectors.


![t1](https://cloud.githubusercontent.com/assets/24231261/21612999/b709f1e6-d1e8-11e6-8ff2-9e1c6efda7f9.PNG)

**Comment by mehrzad69** [comment]
@mimarilker thank you so much. I will do research about similarity types. Do you suggest any links to start?

**Comment by TheodoreGalanos** [comment]
Hi @mehrzad69  I will take a look at your case today.

Btw, this is the pressure vectors and not velocity ones. So if you feel that the vectors are not showing any turbulence, that might be the reason.

Kind regards,
Theodore.

**Comment by mehrzad69** [comment]
@mostaphaRoudsari  The problem is that if the test geometry dimensions are bigger than limits, vectors are not showing any turbulence in an outdoor analysis. so I decided to change the scale of test geometry.

**Comment by TheodoreGalanos** [comment]
Hi @mehrzad69 As I mentioned in my previous post the image you posted above is showing the pressure which will never show any kind of turbulence in the vector representation.

Can you please post the velocity vector visualization?

Kind regards,
Theodore.

**Comment by mimarilker** [comment]
the problem is with meshing settings, I took the same results when I tried to use only block mesh for simulation, and we discussed this issue with @Mostapha yesterday. Its very clear in the velocity vectors  that Mehrzad shared. So as we all see there is no effect of obstacles in the results, the solution is to linking blockmesh not directly to simulation case and using snappyhexmesh for simulation, thats it.

As a brief knowledge, blockmesh just a base for snappyhexmesh and cannot be used for simulation directly. Its aim is dividing domain into the segments according to the requirements of a spesific case, actually that is not an automated process, so user do this manually at current, however I aim to write a gh component doing thia automatically considering cfd best practice guidelines.

**Comment by TheodoreGalanos** [comment]
You could mesh with blockMesh, but only very simple shapes. you can for example draw vertices, boxes, spheres etc. So a simple box building can be done in blockMesh. But it's so tedious to do. Unless someone find an automatic way to generate shapes from Rhino into blockMeshdict files I'd say we stay away from that one.

**Comment by mostaphaRoudsari** [comment]
> @mostaphaRoudsari The problem is that if the test geometry dimensions are bigger than limits, vectors are not showing any turbulence in an outdoor analysis. so I decided to change the scale of test geometry.

This is wrong. If you check the bounding box you can see that it re-sizes based on the size of the building. In other you don't need to scale your building at all. Just make sure to set up the meshing parameters correctly.

![image](https://cloud.githubusercontent.com/assets/2915573/21753613/b244e6a0-d5be-11e6-8cbc-d23142f681e2.png)

The mesh is also fine if you run both `blockMesh` and `snappyHexMesh`. Make sure to pick reasonable values for grading and refinements.
