### ISSUE TITLE
Butterfly flies freely:)

### ISSUE THREAD

**Issue by mimarilker** [ladybug-analysis-tools/butterfly#141]
I am nearly coming to an end on solving butterfly run issues such as "host is not running" or "didnt find the container" etc. Just wanted to make you hear the news!

**Comment by TheodoreGalanos** [comment]
@mimarilker 
That's amazing! Let us know of the progress!

**Comment by mostaphaRoudsari** [comment]
@mimarilker should we close this now that you added the directions for installation?

**Comment by mimarilker** [comment]
yes, as you know it doesnt seem possible to run BF without administrator priviliges, for those who are not experienced with vm, docker or container system can use the instructions as u said. I will continue to seek for a workaround for non-admin. users. It is very important for the students using lab computers as u mentioned.
