### ISSUE TITLE
Butterfly repository is transferred under ladybug-analysis-tools

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/butterfly#148]
All,

Just wanted let you all know that I transferred butterfly library under `ladybug-analysis-tools` organization as we're getting ready for the public release. The links will be redirected so most of the stuff should work fine. Please let us know if you face any issues.

Cheers,
Mostapha

**Comment by mimarilker** [comment]
Is it just a clone of this reprository ? I mean we will continue to write from here, wont we?

**Comment by mostaphaRoudsari** [comment]
@mimarilker this is the exact same repository. I just changed the ownership from my account to ladybug-analysis-tools. The history and everything else stays as it used to be.

**Comment by mostaphaRoudsari** [comment]
This seems not to create any issues.
