### ISSUE TITLE
Segment Grading

### ISSUE THREAD

**Issue by mimarilker** [ladybug-analysis-tools/butterfly#152]
There is a limitation with segment grading, you can just use it for xyz directions, however it is required to be used for negative directions (like -y), is there a way to handle that. Check below for required segment grading. It decreases first, then its stable, lastly it increases, with current grading comp, unfotunately, its  not possible.

![segment](https://cloud.githubusercontent.com/assets/22752273/21748837/1f2f6154-d598-11e6-8b3b-40e4956e2fc3.JPG)

**Comment by mimarilker** [comment]
I have found a way for this at this link https://openfoamwiki.net/index.php/BlockMesh#Generating_multi-graded_meshes

Thats the result!
![segment2](https://cloud.githubusercontent.com/assets/22752273/21748965/d26a4592-d59b-11e6-96c0-0435af7389bb.JPG)

**Comment by mostaphaRoudsari** [comment]
@mimarilker I'm not sure what's the issue here. I believe you can already do this with butterfly.

**Comment by mimarilker** [comment]
yes, u re right, actually its an OF knowledge and a bit tricky.

**Comment by mostaphaRoudsari** [comment]
Then let's close this! It can be confusing. I saw your note up there but closed issues will also come up in searches.
