### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by mimarilker** [ladybug-analysis-tools/butterfly#153]
Instructions for Win10 are added to https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes

Besides, there will be a tutorial video soon.

**Comment by mostaphaRoudsari** [comment]
@mimarilker thanks! Looks good. You can use [markdown ](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)to make it look better.

**Comment by mimarilker** [comment]
Thanks, I will give it a try.

**Comment by DambronOlivier** [comment]
@mimarilker  This is very useful. Thanks!
I've added some additional comments on the Mac side:
https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes-on-Mac
