### ISSUE TITLE
Mesh independency

### ISSUE THREAD

**Issue by mimarilker** [ladybug-analysis-tools/butterfly#156]
Mesh independency is very important to ensure the accuracy of the simulation results. I know that its an OF issue, however for default mesh settings we are using in sample files its crucial, bcs most of the people will just replace the brep geometry in these files and try to get accurate results for all types of geometries. So I advise to run some mesh independency tests for this sample cases and re assign default values for mesh components. I think the current w.tunnel domain size, mesh grading values and mesh cell sizes are not accurate completely (outdoor_airflow case).

**Comment by mostaphaRoudsari** [comment]
@mimarilker can you provide suggestions for the input values? I'm going to assign this to you, and we will see if anybody else has an input on the defaults.

**Comment by mimarilker** [comment]
yes ofc, I have already been working on it, you can assign it to me.
