### ISSUE TITLE
Initial Room Temperature

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-analysis-tools/butterfly#160]
Hi,

In this case, I set the temperatures in the boundary conditions to:
- 7.9°C (281.05K) for the inlet
- 12.6°C (285.75K) for the room walls
- 20.0°C (293.15K) for the boxes

However, in the early time steps the room temperature seems to be at around 27°C (ca. 300K):
![1](https://cloud.githubusercontent.com/assets/23235030/21803015/6f596aee-d728-11e6-805c-8d5896af33af.PNG)

In later time steps everything turns out as one would expect:
![2](https://cloud.githubusercontent.com/assets/23235030/21803040/89232442-d728-11e6-96a5-5bb23e6c194c.PNG)

What determines the initial high room temperature?

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall It is usually the internalField value in the T folder that determines initial temperatures. But that is on iteration 1. Everything changes on iteration 2 and onwards. I wouldn't give much thought to initial steps, it's garbage in terms of results anyways. You should focus on if the residuals are reducing and the temperatures are going towards what is expected.

Kind regards,
Theodore.

**Comment by DambronOlivier** [comment]
hi @MaxMarschall 

Could you share the boundary conditions that you have set for this example? The ones I have been using so far for the heat sources seem to make my simulation diverge.

**Comment by MaxMarschall** [comment]
Hey @DambronOlivier ,

Sorry,  I had a deadline on another project and wasn't able to do CFD in a while. Unfortunately I can't find the definition anymore. Were you able to run your simulation?

**Comment by TheodoreGalanos** [comment]
Closing this one for now.

Let me know if you have any more questions about this.

Regards,
Theodore.
