### ISSUE TITLE
Transient vs. Steady State

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-analysis-tools/butterfly#161]
I have a super basic question that probably stems from my ignorance of CFD...

I was just asked if the simulations I'm doing in BF are transient or steady-state, and I wasn't able to answer with certainty.

Is this even a valid question? Can it be answered in general or does it depend on the solution properties I'm setting? Or can both states be present during a solution?

I figured it was transient since the results change over time (which I thought is what transient means) and the animations look "realistic", but maybe this is just the calculation converging to an ultimately steady state...

Can someone please clarify?

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall All simulations currently in BF are steady-state. It's mostly the issues relating to OF in Windows (e.g. installation problems) that have kept us away from further development that would include transient recipes. 

A steady state can have, and always does have, an iterator (i.e. step). What happens at each step is a better (hopefully) approximation of the same moment in time (steady state). In transiet cases the iterator becomes real time (i.e. seconds) and depends on various parameters (like wind velocity, cell size, etc.).

We will hopefully have a few transient cases in BF. If you want to try some on your own, you can navigate at the beautiful OF tutorials that come with the installation (search for pimpleFOam). They have run files and you can at least see what a transient simulation looks like.

I am also attaching a video of a transient simulation I performed recently, which simulates the impact of a ceiling fan, for your reference.

Kind regards,
Theodore.

[NEAPOLI_PLC_Ceiling Fan transient Simulation.zip](https://github.com/ladybug-analysis-tools/butterfly/files/696017/NEAPOLI_PLC_Ceiling.Fan.transient.Simulation.zip)

**Comment by MaxMarschall** [comment]
Hi @TheodoreGalanos ,

Thanks for explaining that in a way that is understandable to human beings! I did search online but the explanations tend to be unnecessarily geeky.

The video would be great to see, unfortunately it won't play...?

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall You should be able to play it if you have vlc. I made it in Linux, I feel it's ogg vorbis but I forget. VLC plays it though.

Kind regards,
Theodore.

**Comment by TheodoreGalanos** [comment]
Closing this one.
