### ISSUE TITLE
Adjusting simpleFoam and using with butterfly

### ISSUE THREAD

**Issue by mhamadAlloush** [ladybug-analysis-tools/butterfly#169]
Hello,

I'm writing this issue to ask if it is possible to change the openFoam solver used by default in the butterfly plug-in (simpleFoam i.e.). I would, for example, do some changes to simpleFoam like adding a certain equation of interest or anything else, so am I able to implement this new solver?

Regards,
Mhamad

**Comment by thinklikeanarchitect** [comment]
I think its possible, open controlDict.py file and just change the aplication setter's default value from "simple foam" to any other one you desire.

**Comment by TheodoreGalanos** [comment]
@mhamadAlloush 

You can edit and re-compile openfoam solvers quite easily, in Linux. I have not tried to do it in a docker installation in WIndows. I would feel it's really hard and would only work if you compiled the whole package, along with your solver, from scratch.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
A clean way for implementing new solvers is to create a new recipe class. [Here is how the class for SteadyIncompressible](
https://github.com/ladybug-analysis-tools/butterfly/blob/master/butterfly/recipe.py#L324-L354) which uses `simpleFoam`. You can add your own similar to this class or the one for HeatTransfer.

**Comment by mostaphaRoudsari** [comment]
@RomainNouvel sorry for the late reply. I wasn't around for the last two weeks. You should be able to use solutionParameter component to adjust any parameter in any dictionary file.

![image](https://user-images.githubusercontent.com/2915573/29498212-39df4e1e-85c5-11e7-90c9-3a848217cc42.png)

Consider to open a new issue if this didn't work or you couldn't figure out how to get it to work.

**Comment by RomainNouvel** [comment]
Thanks @mostaphaRoudsari, this solutionParameter fits well what I was looking for.
Regards!

**Comment by ZenBel** [comment]
Hi,

Just like Romain, I am trying to have the solutionParameter component to modify fvSchemes in the steady Incompressible Recipe as shown in the picture:

![Screenshot from 2019-11-19 15-26-55](https://user-images.githubusercontent.com/15829498/69154907-230a0500-0ae1-11ea-86b1-1e77f909ab91.png)

but I get the following error:

Runtime error (AssertionException) : fvSolution should be from type FvSolution not <class 'butterfly.solution.SolutionParameter'>

Am I doing something wrong here or is there a bug?

**Comment by carmicheal99** [comment]
Did you get this solved?  I'm having the same challenge.

**Comment by mhamadAlloush** [comment]
Hi,

Well that was long time ago, and I remember it was not easy to do it. In
fact, I couldnt resolve it. What are you willing to run? Are you interested
in automating OpenFOAM?
