### ISSUE TITLE
Error when I try to run the blockmesh component

### ISSUE THREAD

**Issue by frank984** [ladybug-analysis-tools/butterfly#186]
With this new update I have this problem when I try to run the blockmesh component:

![immagine](https://cloud.githubusercontent.com/assets/6491927/22886038/512a1ec6-f1fc-11e6-9663-5091df7237c8.png)

The pop up shows this errors:

1. Solution exception:Error checking TLS connection: Host is not running

	 Docker machine is not running! Run Oracle VM VirtualBox Manager as administrator and make sure "default" machine is "running".

As you can see from the image above, the default machine is running
How can I solve?

**Comment by mostaphaRoudsari** [comment]
Hi @frank984, did you also run Rhino as an administrator? and ran OpenFOAM_start.bat as an admin with no issues?

**Comment by frank984** [comment]
Hi @mostaphaRoudsari ! Rhino runs in administrator mode. At first time I had some issue to run OF_start.bat as an admin, then I turned off the default machine and VBmachine, then I reopened it as an admin and then I reopened the OF_start.bat as an admin without problem. Now I can run the blockmesh component without problems. Tnx!

**Comment by mostaphaRoudsari** [comment]
Great! 👍
