### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by catie-h** [ladybug-analysis-tools/butterfly#190]
Getting this error even I follow the installation steps and update Butterfly with install.gh.
Can someone please help
![butterfly problem](https://cloud.githubusercontent.com/assets/24957418/23070183/2efc0960-f565-11e6-8e98-617caf303805.jpg)

**Comment by DambronOlivier** [comment]
Hi @cathydoa 

after updating, did you quit Grasshopper ,Rhino and relaunched?

**Comment by cathydoa** [comment]
Yes though. I have reinstalled all user objects components into the user objects folder and rerun the installer file in gH.

**Comment by mostaphaRoudsari** [comment]
@cathydoa this component is very old. You need to either manually replace the component or download the updated example file. The component is last updated on `FEB_14_2017`.
https://github.com/ladybug-analysis-tools/butterfly/blob/master/plugin/grasshopper/src/Butterfly_Create%20Case%20from%20Tunnel.py#L79

**Comment by cathydoa** [comment]
Do you mind showing how can I manually reinstall the updated py files to make everything works?

**Comment by catie-h** [comment]
Sorry sir, it is not working still. Even though I have replace the py and get the new battery.
![problem2](https://cloud.githubusercontent.com/assets/24957418/23091131/12d73c2a-f5ea-11e6-9d3c-d97740a7165f.jpg)

**Comment by mostaphaRoudsari** [comment]
@catie-h, Can you upload the output of the butterfly component? Let's make sure it loads the library from the right place.

![image](https://cloud.githubusercontent.com/assets/2915573/23097135/958c4010-f5fa-11e6-9519-5dd4a27e3f9e.png)

If you don't see a similar output to this image then you probably haven't restarted Rhino or updating the libraries has failed.

**Comment by catie-h** [comment]
![installer pic](https://cloud.githubusercontent.com/assets/24957418/23098106/8a0698cc-f680-11e6-9772-f32495c7e4ad.jpg)
I got the same thing though.

**Comment by mostaphaRoudsari** [comment]
Great! Can you try to open [this file](https://github.com/ladybug-analysis-tools/butterfly/blob/master/plugin/grasshopper/samplefiles/outdoor_airflow.gh?raw=true)?

**Comment by catie-h** [comment]
hold on, trying to restart my rhino as administrator

**Comment by catie-h** [comment]
![outflow](https://cloud.githubusercontent.com/assets/24957418/23098145/f8ee3a28-f681-11e6-8db9-e516bffedfbf.jpg)
Weird, the old battery works.

**Comment by mostaphaRoudsari** [comment]
Great! Should we close this issue then? The restart was the key to reload the libraries in Rhino.

**Comment by catie-h** [comment]
Ok. Thanks
