### ISSUE TITLE
OpenFOAM Installation Problem for Running Simulation Via BF 

### ISSUE THREAD

**Issue by amirtabadkani** [ladybug-analysis-tools/butterfly#194]
Hi @mostaphaRoudsari @TheodoreGalanos , 

I have stuck in the OF installation process while I reinstalled it around 10 times and reading all the possible issues here or on the grasshopper3d website ,, but still I can not run the simulation with the latest version of butterfly V3..

I noticed whenever I run Of-Start whether as administrator or not, it gives an error that the default machine has stopped .. Even at end of the OF installation when it runs the power-shell window , It says the ''default'' has stopped .. (I put the related images ) .. and also there is sth wrong with of_v1612plus-centos66 container that can not be created .. 

I really appreciate if you help me with this ,, it took me so much time ...

Thanks ...
![00](https://cloud.githubusercontent.com/assets/17779829/23158431/6e8e4d78-f834-11e6-9ff9-5be1103780c7.png)
![11](https://cloud.githubusercontent.com/assets/17779829/23158436/71418da0-f834-11e6-9ff2-d1539322a464.png)
![213](https://cloud.githubusercontent.com/assets/17779829/23158484/9cc75f22-f834-11e6-93d2-4cc4ba7020ea.png)

**Comment by mostaphaRoudsari** [comment]
I hope @thinklikeanarchitect can help you with this. He knows much more about the installation issues.

**Comment by thinklikeanarchitect** [comment]
Have you followed the instructions that I wrote for installation on Windows 10 ?

https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes

**Comment by DambronOlivier** [comment]
Whenever you re install everything, make sure to uninstall all applications before, boot2docker as well.

**Comment by amirtabadkani** [comment]
Hi @thinklikeanarchitect , 

Thanks for your reply.. Yes I have done all the steps but still no changes .. and I get this error in Grasshopper Canvas and while I try to run virtualbox I get the other error .. I ve seen these errors in other issues that others have posted but I couldnt solve mine ,..

Thanks ..

![canvas at 10 10 31](https://cloud.githubusercontent.com/assets/17779829/23200049/5d11376e-f8e7-11e6-9bac-7ff801877ef2.png)
![untitled](https://cloud.githubusercontent.com/assets/17779829/23200051/5e2f00ae-f8e7-11e6-83e4-7a9179ed4ea8.png)

**Comment by amirtabadkani** [comment]
Hi @DambronOlivier 
Yes I have uninstalled all the parts related to OF each time I reinstall it ..

**Comment by MikkiSeidenschnur** [comment]
I see that your username has whitespaces (win 8.1). That might be an issue: #176 we've encountered before

Best regards
Mikki

**Comment by amirtabadkani** [comment]
Thanks @MikkiSeidenschnur ,, Do you know an easy way to change the user name in C drive ? I searched for it ,, it seems difficult..

**Comment by mostaphaRoudsari** [comment]
@amirtabadkani what about creating a new user?

**Comment by MikkiSeidenschnur** [comment]
I found this [thread](https://www.groovypost.com/howto/rename-local-windows-10-user-account/) online that described how to change it. However, I had to reinstall the system anyway, so I just created the user upon the windows 10 reinstall

**Comment by amirtabadkani** [comment]
@MikkiSeidenschnur The whitespace was the problem .. I really appreciate your help ; however it seems a bit weired , only this small gap makes a huge issue in installation .. 

I again thanks all who particpicated in this issue and I will close it ..

**Comment by TheodoreGalanos** [comment]
@amirtabadkani Glad you resolved the issue! OpenFOAM is terribly allergic to empty spaces, in the future make sure that your folders also do not include an empty space. After a while, it's almost a routine to name them so don't worry :)

Regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
We should add this somewhere to the installation instructions!
