### ISSUE TITLE
running example files - outdoor_study.dyn

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-analysis-tools/butterfly#201]
outdoor_study.dyn
I just installed everything and trying to run samples outdoor_study.dyn,
I can see that even when I am running example with everything set to no there are warnings,
same when I change to True. 

WindVector
![image](https://cloud.githubusercontent.com/assets/14005893/23343152/bf473bac-fc5e-11e6-916e-190ed2eca5d1.png)

**Comment by mostaphaRoudsari** [comment]
Hi @mdengusiak! Thank you for testing and reporting this. Can you insert a new 'Wind Vector' node from butterfly tab and try again? Not sure what's going on inside Dynamo.

**Comment by mostaphaRoudsari** [comment]
I just checked and it works totally fine on my machine:
![image](https://cloud.githubusercontent.com/assets/2915573/23343770/a26cf352-fc3e-11e6-8ce3-cd205c3e58d5.png)

**Comment by mdengusiak** [comment]
I added new and same issue,

![image](https://cloud.githubusercontent.com/assets/14005893/23343845/baae75fa-fc69-11e6-99e9-08b64cbbcf7a.png)

**Comment by mostaphaRoudsari** [comment]
The issue was that Dynamo didn't import `Autodesk` namespace by default. `Vector` needs to be changed to `Autodesk.Vector`

**Comment by mdengusiak** [comment]
Another issue is with Point. 
We need to add Autodesk.Point

![image](https://cloud.githubusercontent.com/assets/14005893/23344646/0cad0bf6-fc78-11e6-979a-243b80a42292.png)


// Cell size in (x, y, z) as a tuple (default: length / 5).
// This value updates number of divisions in blockMeshDict.
_cellSizeXYZ_: Point = null;

also at Mesh step there is some issue with OpenFoan Container
![image](https://cloud.githubusercontent.com/assets/14005893/23344707/d9db91ec-fc78-11e6-8405-527d6a4a24a6.png)

**Comment by mostaphaRoudsari** [comment]
@mdengusiak fixed the issue with namespace. Download the new version from package manager and give it a try. We will solve the other issue under #202

**Comment by pedobohufg** [comment]
Hello! Can you help me with this issue? 
![image](https://user-images.githubusercontent.com/52789910/61058097-f6284180-a3cc-11e9-8555-5a7e7125e19d.png)
