### ISSUE TITLE
start writing dynamo libraries

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/butterfly#64]
I hope what I have learned from the honeybee side makes this one faster. I will get this started after butterfly 0.0.02 is out.

**Comment by bitacovir** [comment]
@mostaphaRoudsari
Is this dynamo bim?
Do you know sverchok? 
http://nikitron.cc.ua/sverchok_en.html

**Comment by mostaphaRoudsari** [comment]
@bitacovir yes and yes. I have never worked with sverchok though. [Butterfly geometry libraries](https://github.com/mostaphaRoudsari/Butterfly/tree/master/butterfly/gh) are very minimal (). If someone rewrites them for sverchock then there will be a 3rd Butterfly plugin.

Also I think there is already an OpenFOAM plugin for Blender.

**Comment by bitacovir** [comment]
Yes. It is ODS-Studio https://www.ods-engineering.com/tools/ods-studio/download/
I have used it. However, butterfly looks much more user-friendly. And it can perform indoor simulation. ODS-Studio (free version) only works for outdoor simulation, I think.

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/20123271/faecd366-a5eb-11e6-8947-18d7e69a7aa4.png)

**Comment by mostaphaRoudsari** [comment]
Now this is for real!
![image](https://cloud.githubusercontent.com/assets/2915573/22953764/8eed1dfa-f2e0-11e6-8dba-256c3aa9b0bf.png)

**Comment by thinklikeanarchitect** [comment]
excellent!

**Comment by mostaphaRoudsari** [comment]
need to re-write `solution`, `residuals` and `decomposePar`. All of them are using GH specific functionalities.

**Comment by mostaphaRoudsari** [comment]
Boom!
![image](https://cloud.githubusercontent.com/assets/2915573/23221854/24f575ea-f8f4-11e6-8ec3-6d71f94e6ae9.png)

**Comment by mostaphaRoudsari** [comment]
addressed via https://github.com/ladybug-analysis-tools/butterfly/commit/c3123c4add2e444aa0e93f8c8ffdb990cd563da0

@bitacovir if you're still interested in a connection with sverchok please open a new issue.
